[package]
name = "sauce_help"
version = "0.1.0"
authors = ["mdsauce <max.dobeck@saucelabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.102"
reqwest = "0.9.22"
serde_json = "1.0.41"