[package]
name = "build_metadata"
version = "0.1.0"
authors = ["mdsauce <max.dobeck@saucelabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
